version: "3.8"

services:
  # GoEth PoA Node
  goeth:
    image: ethereum/client-go:latest
    container_name: blockcred-goeth
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ./blockchain-data:/root/.ethereum
      - ./genesis.json:/genesis.json
    command: >
      --datadir /root/.ethereum
      --networkid 1337
      --syncmode full
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.api eth,net,web3,personal,admin
      --http.corsdomain "*"
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.api eth,net,web3,personal,admin
      --ws.origins "*"
      --unlock 0x742d35Cc6634C0532925a3b8D0C0C4C4C4C4C4C4
      --password /root/.ethereum/password.txt
      --mine
      --miner.threads 1
      --miner.etherbase 0x742d35Cc6634C0532925a3b8D0C0C4C4C4C4C4C4
    networks:
      - blockchain

  # BlockCred Backend
  backend:
    build: .
    container_name: blockcred-backend
    ports:
      - "8080:8080"
    environment:
      - BLOCKCHAIN_RPC_URL=http://goeth:8545
      - BLOCKCHAIN_PRIVATE_KEY=your-private-key-here
      - BLOCKCHAIN_CONTRACT_ADDRESS=your-contract-address-here
    depends_on:
      - goeth
    networks:
      - blockchain

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: blockcred-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./blockcred_rules.yml:/etc/prometheus/blockcred_rules.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: blockcred-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring

networks:
  blockchain:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
